import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { Socket } from 'node:net';

// Imported backend modules may construct clients, but none may open outbound sockets.
Socket.prototype.connect = function () {
  throw new Error('Outbound sockets are forbidden in the isolated integration server.');
} as typeof Socket.prototype.connect;
process.chdir(fileURLToPath(new URL('.', import.meta.url)));
process.env.NODE_ENV = 'test';
process.env.API_KEYS_JSON = JSON.stringify([{ key: 'isolated-integration-key', name: 'integration' }]);
for (const key of ['DB_PASSWORD', 'DB_USER', 'DB_NAME', 'DB_HOST', 'DB_PORT', 'K_SERVICE', 'INSTANCE_CONNECTION_NAME', 'GOOGLE_APPLICATION_CREDENTIALS']) delete process.env[key];

const require = createRequire(new URL('../../../cloud-api-server/package.json', import.meta.url));
const { PGlite } = require('@electric-sql/pglite');
const express = require('express');
const { initializeApp } = require('firebase-admin/app');
const { getAuth } = require('firebase-admin/auth');
const firebase = initializeApp({ projectId: 'isolated-integration' });
const identities = new Set(['staff-a', 'staff-b', 'member']);
// Test-only verification; production userAuth still parses claims and enforces route roles.
getAuth(firebase).verifyIdToken = async (token: string) => {
  const uid = token.replace(/^isolated-test-/, '');
  if (!token.startsWith('isolated-test-') || !identities.has(uid)) throw new Error('Unknown synthetic token');
  return { uid, sub: uid, aud: 'isolated-integration', iss: 'isolated-integration', iat: 0, exp: 9999999999, staff: uid.startsWith('staff-') };
};

let pg = new PGlite();
let queue = Promise.resolve();
const run = (text: string, values: any[] = []) => pg.query(text, values);
const { pool } = await import('../../../cloud-api-server/src/config/db.js');
// OperationService and read controllers both retain this exact exported pool object.
(pool as any).query = run;
(pool as any).connect = async () => {
  let unlock!: () => void;
  const previous = queue;
  queue = new Promise<void>(resolve => { unlock = resolve; });
  await previous;
  return { query: run, release: unlock };
};
const { createApp } = await import('../../../cloud-api-server/src/app.js');
const migration = await readFile(new URL('../../../cloud-api-server/migrations/003_operation_groups.sql', import.meta.url), 'utf8');
let calls: any[] = [];
let conflict = false;
async function reset() {
  await pg.close();
  pg = new PGlite();
  await pg.exec(`CREATE TABLE events(id bigint PRIMARY KEY,start_at timestamptz NOT NULL,end_at timestamptz,title text);
    CREATE TABLE contacts(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL,created_on timestamptz DEFAULT clock_timestamp(),emails text[],phones text[],zip_home text,zip_other text[],roles text[],firebase_uid text);
    CREATE TABLE checkins(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,contact_id bigint REFERENCES contacts(id),event_id bigint NOT NULL REFERENCES events(id),submitted_on timestamptz NOT NULL);
    INSERT INTO events VALUES(1,'2026-10-03 18:00Z','2026-10-03 20:00Z','Synthetic event');
    INSERT INTO contacts(id,name,created_on,emails,phones,zip_home,zip_other,roles,firebase_uid) VALUES
      (1,'ALICE ORIGINAL','2026-09-01 12:34:56.654321Z',ARRAY['second@example.invalid','first@example.invalid'],NULL,NULL,ARRAY['75202','75201'],ARRAY['member','volunteer'],'staff-a'),
      (2,'BOB ORIGINAL','2026-09-01 12:34:56.123456Z',NULL,ARRAY['+1-214-555-0100'],NULL,NULL,NULL,'member');
    INSERT INTO checkins VALUES(1,1,1,'2026-10-03 18:00:00.123456Z'),(2,2,1,'2026-10-03 18:01:00.987654Z');`);
  await pg.exec(migration);
  calls = [];
  conflict = false;
}
await reset();

const app = express();
app.use(express.json({ limit: '2mb' }));
app.get('/__integration/ready', (_req: any, res: any) => res.json({ isolated: true }));
app.post('/__integration/reset', async (_req: any, res: any) => { await reset(); res.json({ reset: true }); });
app.post('/__integration/conflict', (_req: any, res: any) => { conflict = true; res.json({ armed: true }); });
app.get('/__integration/state', async (_req: any, res: any) => {
  // Cast timestamps in SQL: JS Date would silently truncate PostgreSQL microseconds.
  const contacts = await run('SELECT id::text,name,created_on::text,emails,phones,zip_home,zip_other,roles,firebase_uid FROM contacts ORDER BY id');
  const checkins = await run('SELECT id::text,contact_id::text,event_id::text,submitted_on::text FROM checkins ORDER BY id');
  const groups = await run('SELECT id::text,owner_uid,state,commit_order::text FROM operation_groups ORDER BY created_at,id');
  res.json({ contacts: contacts.rows, checkins: checkins.rows, groups: groups.rows, calls });
});
app.use(async (req: any, _res: any, next: any) => {
  if (req.path.startsWith('/api/')) {
    calls.push({ method: req.method, path: req.path, uid: req.header('Authorization')?.replace('Bearer isolated-test-', ''), body: req.body,
      match: req.header('If-Match'), group: req.header('X-Operation-Group'), key: req.header('Idempotency-Key') });
    if (conflict && req.method === 'POST' && /\/commit$/.test(req.path)) {
      conflict = false;
      // Deterministic outside writer after every stage, before the real atomic commit.
      await run("UPDATE checkins SET submitted_on='2026-10-03 18:02:00.777777Z' WHERE id=1");
    }
  }
  next();
});
app.use(createApp());
const server = app.listen(4196, '127.0.0.1', () => console.log('Isolated integration API listening on 127.0.0.1:4196'));
async function shutdown() {
  server.close();
  await pg.close();
  await pool.end();
  process.exit(0);
}
process.once('SIGINT', shutdown);
process.once('SIGTERM', shutdown);
